config/routes.rb
require 'sidekiq/web'

Trado::Application.routes.draw do
	  root to: 'store#home'

  	# Custom routes
  	get '/search' => 'search#results'
  	get '/search/autocomplete' => 'search#autocomplete'

  	# Error pages
  	%w( 404 422 500 ).each do |code|
  		get code, to: "errors#show", code: code
  	end

  	# Pages system
  	namespace :p do
  		get ':slug', to: 'pages#show'
  		resources :pages, only: [] do
  			post :send_contact_message, on: :collection
  		end
  	end

  	devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }
  	resources :users
  	resources :contacts, only: :create
  

  	resources :categories, only: :show do
  		resources :products, only: :show
  	end

    resources :products, only: [] do
      resources :skus, only: [] do
        member do
          get :update        
        end
      end
      resources :accessories, only: [] do
          get :update, on: :collection
      end
    end

    resources :skus, only: [] do
      resource :notify_me, only: [:new, :create], controller: 'products/notify_me'
    end
  
  	resources :carts, only: [] do
  		collection do
	  		get :mycart
	  		get :checkout
        %w( paypal stripe ).each do |payment|
          post "#{payment}/confirm", to: "carts/#{payment}#confirm", as: "#{payment}_confirm"
        end
  		end
  	end
    resources :cart_items, only: [:create, :update, :destroy]
    resources :delivery_service_prices, only: [:show]

  	resources :orders, only: [:destroy] do
  		member do
	  		get :retry
	  		get :confirm
	  		post :complete
  		end
      collection do
        get :success
        get :failed
      end
  		resources :addresses, only: [:new, :create, :update]
  	end

  	namespace :admin do
  		root to: "admin#dashboard"
  		authenticate :user, lambda { |u| u.role?(:admin) } do
	  		mount RedactorRails::Engine => '/redactor_rails'
	  		mount Sidekiq::Web => '/sidekiq'
  		end
	  	resources :accessories, :categories, except: :show
	  	resources :products, except: [:show, :create] do
        member do
          patch :autosave
          patch :archive
        end
	  		resources :attachments, except: :index
	  		resources :skus, except: [:index, :show] do
	  			resources :stock_adjustments, only: [:create, :new], controller: 'skus/stock_adjustments'
	  		end
	  		namespace :skus do
	  			resources :sku_variants, as: 'variants', path: 'variants', controller: :variants, only: :new do
	  				collection do
              post 'create', as: 'create'
	  					patch 'update', as: 'update'
	  					delete 'destroy', as: 'destroy'
	  				end
	  			end
	  		end
	  	end
  		resources :orders, only: [:index, :show, :update, :edit] do
        delete :cancel, to: 'orders#cancel', on: :member
      end
      resources :transactions, only: :show
  		resources :delivery_services, except: :show do
	  		collection do
	  			get :copy_countries
	  			post :set_countries
	  		end
  			resources :delivery_service_prices, path: 'prices', except: :show
  		end
  		namespace :products do
  			resources :tags, only: :index
  			resources :stock, only: [:index, :show]
        resources :stock_adjustments, only: [:new, :create]
  		end
	  	resources :pages, except: [:show, :destroy, :new, :create]
	  	get '/settings' => 'admin#settings'
	  	patch '/settings/update' => 'admin#update'
	  	get '/profile' => 'users#edit'
	  	patch '/profile/update' => 'users#update'
  	end

  	# # redirect unknown URLs to 404 error page
  	# match '*path', via: :all, to: 'errors#show', code: 404
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::AdminBaseController
  include PaginationHelper
  before_action :authenticate_user!
  layout 'admin'

  def index
    set_delivery_status
    set_payment_type
    set_orders
  end

  def show
    set_order
  end

  def edit
    set_order
    render json: { modal: render_to_string(partial: 'admin/orders/modal') }, status: 200
  end

  def update
    set_order
    @order.validate_shipping_date!
    if @order.update(params[:order])
      OrderMailer.updated_dispatched(@order).deliver_later if @order.updated_delivery_details?
      render json: 
      { 
        order_id: @order.id,
        date: @order.shipping_date.strftime("%d/%m/%Y %R"),
        row: render_to_string(partial: 'admin/orders/single', locals: { order: @order }),
        dispatch_date: @order.shipping_date.strftime(" #{@order.shipping_date.day.ordinalize} %b %Y"),
        tracking: render_to_string(partial: 'admin/orders/tracking', locals: { order: @order })
      }, status: 200
    else 
      render json: { errors: @order.errors.full_messages }, status: 422
    end
  end

  def cancel
    set_order
    @order.cancelled!
    @order.restore_stock!
    redirect_to admin_orders_url
  end
  
  private

  def set_order
    @order ||= Order.complete.find(params[:id])
  end

  def set_orders
    @orders ||= Order.includes(:billing_address).complete.where(shipping_status: @delivery_status).where(payment_type: @payment_type).order(created_at: :desc).page(page).per(limit)
  end

  def set_delivery_status
    @delivery_status = params[:delivery_status].present? ? (params[:delivery_status] == "all" ? Order.shipping_statuses.values : (Order.shipping_statuses.values.include?(params[:delivery_status].to_i) ? params[:delivery_status] : Order.shipping_statuses.values)) : Order.shipping_statuses.values
  end

  def set_payment_type
    @payment_type = params[:payment_type].present? ? (params[:payment_type] == "all" ? Order.payment_types.values : (Order.payment_types.values.include?(params[:payment_type].to_i) ? params[:payment_type] : Order.payment_types.values)) : Order.payment_types.values
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    skip_before_action :authenticate_user!
    include CartBuilder

    def confirm
      set_order
      set_address_variables
      validate_confirm_render
    end

    def complete
      set_order
      if @order.completed?
        return render_order_already_completed 
      end

      redirect_url = Store::PayProvider.new(order: @order, provider: @order.payment_type, session: session, ip_address: request.remote_ip).complete
      redirect_to redirect_url
    end

    def success
      set_session_order
      if @order.latest_transaction.pending? || @order.latest_transaction.completed?
        render theme_presenter.page_template_path('orders/success'), layout: theme_presenter.layout_template_path
      else
        redirect_to root_url 
      end
    rescue ActiveRecord::RecordNotFound
      redirect_to root_url
    end

    def failed
      set_session_order
      if @order.latest_transaction.failed?
        render theme_presenter.page_template_path('orders/failed'), layout: theme_presenter.layout_template_path
      else
        redirect_to root_url
      end
    rescue ActiveRecord::RecordNotFound
      redirect_to root_url
    end

    def retry
      set_order
      if Modulatron4000.paypal? && TradoPaypalModule::Paypaler.fatal_error_code?(@order.last_error_code)
        Payatron4000.decommission_order(@order)
      end
      redirect_to mycart_carts_url
    end

    def destroy
      set_order
      Payatron4000.decommission_order(@order)
      flash_message :success, t('controllers.orders.destroy.valid')
      redirect_to root_url
    end

    private

    def set_session_order
      @order = Order.active.includes(:delivery_address).find(session[:order_id])
    end

    def set_order
      @order ||= Order.active.find(params[:id])
    end

    def set_eager_loading_order
      @order ||= Order.active.includes(:delivery_address, :billing_address).find(params[:id])
    end

    def set_address_variables
      @delivery_address = @order.delivery_address
      @billing_address = @order.billing_address
    end

    def validate_confirm_render
      if Payatron4000.order_pay_provider_valid?(@order, params)
          TradoPaypalModule::Paypaler.assign_paypal_token(params[:token], params[:PayerID], @order) if @order.paypal?
          render theme_presenter.page_template_path('orders/confirm'), layout: theme_presenter.layout_template_path
      else
        flash_message :error, t('controllers.orders.validate_confirm_render.invalid')
        redirect_to checkout_carts_url
      end
    end

    def render_order_already_completed
        redirect_to success_orders_url, notice: 'Your order has already been completed'
    end
end

app/helpers/order_helper.rb
require 'modulatron_4000'

module OrderHelper

    def status_label record, status
        if record.class == Order
            class_name = record.dispatched? ? 'green' : record.pending? ? 'orange' : 'red'
        elsif record.class == Transaction
            class_name = record.completed? ? 'green' : record.pending? ? 'orange' : 'red'
        end
      "<span class='label label-#{class_name} label-small'>#{status.capitalize}</span>".html_safe
    end

    def order_filter_classes order
        return order.dispatched? ? "order-dispatched" : "order-pending"
    end

    def checkout_pay_provider_path
        Modulatron4000.paypal? ? paypal_confirm_carts_path : Modulatron4000.stripe? ? stripe_confirm_carts_path : ""
    end
    def pending_delivery_time order
        "<i class='icon-clock label label-blue label-small' data-placement='bottom' data-toggle='tooltip' data-original-title='Delivery Date Set'></i>".html_safe if order.has_pending_delivery_datetime?
    end

    def delivery_filter_select
        [
            ["Show All", "all"],
            ["Dispatched", 1],
            ["Pending", 0]
        ]
    end 

    def payment_filter_select
        [
            ["Show All", "all"],
            ["Paypal", 0],
            ["Stripe", 1]
        ]
    end
end

app/views/admin/orders/_modal.html.erb
<div aria-hidden="true" aria-labelledby="orderModalLabel" class="modal fade" id="order-form" role="dialog" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_for [:admin, @order], html: { role: 'form', method: :patch, id: @order.id }, remote: true, format: :json do |f| %>
        <div class="json" id="errors">
          <ul></ul>
        </div>
        <%= render partial: 'shared/loading', format: [:html] %>
        <div class="modal-header">
          <h3 id="orderModalLabel">
            <%= t('orders.edit.modal.header') %>
            <%= "##{@order.id}" %>
          </h3>
        </div>
        <div class="modal-body">
          <fieldset class="widget widget-content widget-last">
            <div class="form-group">
              <%= f.label t('orders.edit.modal.dispatch_date_label') %>
              <%= f.text_field :shipping_date, class: 'form-control datetimepicker', value: (@order.shipping_date.strftime('%d/%m/%Y %R') unless @order.shipping_date.nil?) %>
             </div>
            <div class="form-group form-last">
              <%= f.label t('orders.edit.modal.consignment_number_label') %>
              <%= f.text_field :consignment_number, :class => 'form-control' %>
            </div>
          </fieldset>
        </div>
        <div class="modal-footer">
          <button class="btn btn-orange btn-large" data-dismiss="modal" type="button"><%= t('modal.close_button') %></button>
          <%= f.submit t('orders.edit.modal.submit_button'), :class => 'btn btn-blue btn-large' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/orders/_shipping_form.html.haml
#shipping-form.modal.fade{"aria-hidden" => "true", style: "display: none;", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .widget.widget-blue
        .widget-title
          %h3
            %i.icon-signal
            = "Update shipping: ##{@order.id}"
        .widget-content
          .modal-body
            = form_for [:admin, @order], :html => { :class => 'form-horizontal', :role => 'form', :method => "put" } do |f|
              .form-group
                = f.label :shipping_date, :class => 'control-label col-md-3'
                .col-md-9
                  = f.text_field :shipping_date, :class => 'form-control', 'data-behaviour' => 'datepicker', :autocomplete => 'off', :value => (@order.shipping_date.blank? ? '' : @order.shipping_date.strftime('%d/%m/%Y'))
              .form-group
                .col-md-offset-3.col-md-9
                  = f.submit 'Submit', :class => 'btn btn-primary'
                  %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close

app/views/admin/orders/_single.html.erb
<td>
  <%= order.id %>
</td>
<td>
    <%= order.billing_address.full_name %>
</td>
<td>
    <%= order.customer_payment_type %>
</td>
<td>
  <%= status_label order.latest_transaction, order.latest_transaction.payment_status %>
</td>
<td>
  <%= status_label order, order.shipping_status %>
  <%= pending_delivery_time(order) %>
</td>
<td>
  <%= Store::Price.new(price: order.gross_amount).single %>
</td>
<td>
  <%= order.updated_at.strftime('%d/%m/%Y at %I:%M%p') %>
</td>
<%= table_actions [:admin, order], 'show', 'remote-edit' %>

app/views/admin/orders/_success.js.erb
$('#order-form').modal('hide');
trado.animation.alert(
    '.widget-header', 
    'success', 
    'order-update-alert',
    '<i class="icon-checkmark-circle"></i>Successfully updated dispatch details for Order #<%= @order.id %> to <%= @order.shipping_date.strftime("#{@order.shipping_date.day.ordinalize} %b %Y") %>.',
    5000
)

app/views/admin/orders/_tracking.html.erb
<% if @order.tracking? %>
    <div>
        <p><b><%= t('orders.show.tracking.website') %>:</b> <%= link_to Store.tracking_url(order.delivery_service.tracking_url, order.consignment_number), Store.tracking_url(order.delivery_service.tracking_url, order.consignment_number), target: '_blank' %></p>
    </div>
    <div>
        <p><b><%= t('orders.show.tracking.number') %>:</b> <%= order.consignment_number %></p>
    </div>
<% end %>

app/views/admin/orders/index.html.erb
<% content_for :title, t('orders.index.title') %>
<% content_for :breadcrumb, t('orders.index.breadcrumb') %>
<% javascript :footer, 'admin/soca.datepicker' %>

<div class="twelvecol">
  <div class="page-header">
    <h2 class="widget widget-header"><%= t('orders.index.header') %></h2>
  </div>
  <div class="widget-controls">
    <%= form_tag admin_orders_path, method: :get do %>
      <%= submit_tag "Search", :class => 'btn btn-blue btn-normal' %>
      <%= select_tag :delivery_status, options_for_select(delivery_filter_select, params[:delivery_status]), { include_blank: false, :class => 'form-select' } %>
      <span><%= t('orders.index.delivery_select') %>:</span>
      <%= select_tag :payment_type, options_for_select(payment_filter_select, params[:payment_type]), { include_blank: false, :class => 'form-select' } %>
      <span><%= t('orders.index.payment_select') %>:</span>
    <% end %>
  </div>
  <% if @orders.empty? %>
    <div class="widget widget-content">
      <div class="helper-notification">
        <p><%= t('orders.index.no_records') %></p>
        <i class="icon-box-add"></i>
      </div>
    </div>
  <% else %>
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
            <th><%= t('orders.index.order_number') %></th>
            <th><%= t('orders.index.full_name') %></th>
            <th><%= t('orders.index.payment_type') %></th>
            <th><%= t('orders.index.payment_status') %></th>
            <th><%= t('orders.index.delivery_status') %></th>
            <th><%= t('orders.index.gross_amount') %></th>
            <th><%= t('orders.index.last_updated') %></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr id="order_<%= order.id %>">
              <%= render partial: 'admin/orders/single', format: [:js], locals: { order: order } %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @orders %>
    </div>
  <% end %>
</div>
<div id="order-modal"></div>
<div id="dispatch-order-modal"></div>

app/views/admin/orders/show.html.erb
<% content_for :title, t('orders.show.title', order_id: @order.id) %>
<% content_for :breadcrumb, "##{@order.id}" %>
<% breadcrumb_add t('orders.show.orders_index'), admin_orders_path %>
<% javascript :footer, 'admin/soca.datepicker' %>

<div class="twelvecol">
  <div class="page-header">
    <%= link_to cancel_admin_order_path(@order), :class => "btn btn-red btn-large", "data-placement" => "bottom", "data-toggle" => "tooltip", title: t('orders.show.cancel_order_tooltip'), method: :delete, data: { confirm: 'Are you sure?' } do %>
      <i class="icon-close"></i>
    <% end %>
    <a href="#" data-record-id="<%= @order.id %>" class="edit-order-record btn btn-blue btn-large" data-placement="bottom" data-toggle="tooltip" title="Edit Order">
      <i class="icon-pencil"></i>
    </a>
    <%= page_header_button(@order) if Modulatron4000.pdf_invoice? %>
    <h2 class="widget widget-header">
      <%= t('orders.show.header', order_id: @order.id) %>
    </h2>
  </div>
</div>
<div class="row order-summary-row">
  <div class="sixcol">
    <div class="widget-sub-heading">
      <h3><%= t('orders.show.delivery_details.header') %></h3>
    </div>
    <div class="widget widget-content" id="delivery-details">
      <div id="email"> 
        <p><b><%= t('orders.show.delivery_details.email') %></b>: <%= @order.email %></p>
      </div>
      <div id="delivery-status">
        <p><b><%= t('orders.show.delivery_details.status') %></b>: <%= status_label @order, @order.shipping_status %></p>
      </div>
      <div id="dispatch-date">
        <p><b><%= t('orders.show.delivery_details.dispatch_date') %></b>: <span><%= @order.shipping_date.present? ? @order.shipping_date.strftime(" #{@order.shipping_date.day.ordinalize} %b %Y") : "None Available"   %></span></p>
      </div>
      <div>
        <p><b><%= t('orders.show.delivery_details.delivery_service') %>:</b> <%= @order.delivery.full_name %></p>
      </div>
      <div id="tracking">
        <%= render partial: 'admin/orders/tracking', format: :html, locals: { order: @order } %>
      </div>
    </div>
  </div>
  <div class="sixcol last">
    <div class="widget-sub-heading">
      <h3><%= t('orders.show.payment_details.header') %></h3>
    </div>
    <div class="widget widget-content">
      <%= image_tag "paypal-icon.png" if Modulatron4000.paypal? && @order.paypal? %>
      <%= stripe_admin_credit_card_data(@order) if Modulatron4000.stripe? && @order.stripe? %>
    </div>
  </div>
</div>
<div class="row order-summary-row">
  <div class="sixcol">
    <div class="widget-sub-heading">
      <h3><%= t('orders.show.billing_address.header') %></h3>
    </div>
    <div class="widget widget-content" id="billing-address">
      <%= @order.billing_address.full_name %>
      <br/>
      <%= @order.billing_address.address %>
      <br/>
      <%= @order.billing_address.city %>
      <br/>
      <%= @order.billing_address.postcode %>
      <br/>
      <%= @order.billing_address.country.name %>
      <br/>
      <br/>
      <%= @order.billing_address.telephone %>
      <br/>
    </div>
  </div>
  <div class="sixcol last">
    <div class="widget-sub-heading">
      <h3><%= t('orders.show.delivery_address.header') %></h3>
    </div>
    <div class="widget widget-content" id="delivery-address">
      <%= @order.delivery_address.full_name %>
      <br/>
      <%= @order.delivery_address.address %>
      <br/>
      <%= @order.delivery_address.city %>
      <br/>
      <%= @order.delivery_address.postcode %>
      <br/>
      <%= @order.delivery_address.country.name %>
      <br/>
      <br/>
      <%= @order.delivery_address.telephone %>
      <br/>
    </div>
  </div>
</div>
<div class="row">
  <div class="twelvecol">
    <div class="widget-sub-heading">
      <h3><%= t('orders.show.order_items.header') %></h3>
    </div>
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover table-margin">
        <thead>
          <tr>
            <th><%= t('orders.show.order_items.item') %></th>
            <th><%= t('orders.show.order_items.sku') %></th>
            <th><%= t('orders.show.order_items.price') %></th>
            <th><%= t('orders.show.order_items.quantity') %></th>
            <th><%= t('orders.show.order_items.total') %></th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_items.each do |item| %>
            <tr>
              <td>
                <%= link_to item.sku.product.name, [item.sku.product.category, item.sku.product] %>
                <div class="item-sub">
                  <%= render_variants(item.sku) unless item.sku.product.single? %>
                </div>
                <% unless item.order_item_accessory.nil? %>
                  <div class="item-sub label label-blue">
                    <%= "<i class='icon-code-fork'></i> #{item.order_item_accessory.accessory.name}".html_safe %>
                  </div>
                <% end %>
              </td>
              <td>
                <%= item.sku.full_sku %>
              </td>
              <td>
                <%= Store::Price.new(price: item.price).single %>
              </td>
              <td>
                <%= item.quantity %>
              </td>
              <td>
                <%= Store::Price.new(price: item.total_price).single %>
              </td>
            </tr>
          <% end %>
          <tr>
            <td class="align-right" colspan="4">
              <b><%= t('orders.show.order_items.delivery') %>:</b>
            </td>
            <td>
              <%= Store::Price.new(price: @order.delivery.price).single %>
            </td>
          </tr>
          <tr>
            <td class="align-right border-top" colspan="4">
              <b><%= t('orders.show.order_items.subtotal') %>:</b>
            </td>
            <td class="border-top">
              <%= Store::Price.new(price: @order.net_amount).single %>
            </td>
          </tr>
          <tr>
            <td class="align-right" colspan="4">
              <b><%= t('orders.show.order_items.tax') %>:</b>
            </td>
            <td>
              <%= Store::Price.new(price: @order.tax_amount).single %>
            </td>
          </tr>
          <tr class="focused">
            <td class="align-right" colspan="4">
              <b><%= t('orders.show.order_items.total') %>:</b>
            </td>
            <td>
              <%= Store::Price.new(price: @order.gross_amount).single %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="widget-sub-heading">
      <h3><%= t('orders.show.transactions.header') %></h3>
    </div>
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover table-last">
        <thead>
          <tr>
            <th><%= t('orders.show.transactions.transaction_type') %></th>
            <th><%= t('orders.show.transactions.payment_type') %></th>
            <th><%= t('orders.show.transactions.payment_status') %></th>
            <th><%= t('orders.show.transactions.fee') %></th>
            <th><%= t('orders.show.transactions.net_amount') %></th>
            <th><%= t('orders.show.transactions.gross_amount') %></th>
            <th><%= t('orders.show.transactions.last_updated') %></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @order.transactions.each do |transaction| %>
            <tr id="transaction_<%= transaction.id %>">
              <td>
                <%= transaction.transaction_type %>
              </td>
              <td>
                <%= transaction.payment_type.titleize %>
              </td>
              <td>
                <%= status_label transaction, transaction.payment_status %>
              </td>
              <td>
                <%= Store::Price.new(price: transaction.fee).single %>
              </td>
              <td>
                <%= Store::Price.new(price: transaction.net_amount).single %>
              </td>
              <td>
                <%= Store::Price.new(price: transaction.gross_amount).single %>
              </td>
              <td>
                <%= transaction.updated_at.strftime('%B %-d, %Y, %I:%M %P') %>
              </td>
              <td>
                <a href="#" class="transaction-info-modal" data-record-id="<%= transaction.id %>">
                  <i class="icon-search"></i>
                </a>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div id="transaction-modal"></div>
<div id="order-modal"></div>