config/routes.rb
require 'sidekiq/web'

Trado::Application.routes.draw do
	  root to: 'store#home'

  	# Custom routes
  	get '/search' => 'search#results'
  	get '/search/autocomplete' => 'search#autocomplete'

  	# Error pages
  	%w( 404 422 500 ).each do |code|
  		get code, to: "errors#show", code: code
  	end

  	# Pages system
  	namespace :p do
  		get ':slug', to: 'pages#show'
  		resources :pages, only: [] do
  			post :send_contact_message, on: :collection
  		end
  	end

  	devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }
  	resources :users
  	resources :contacts, only: :create
  

  	resources :categories, only: :show do
  		resources :products, only: :show
  	end

    resources :products, only: [] do
      resources :skus, only: [] do
        member do
          get :update        
        end
      end
      resources :accessories, only: [] do
          get :update, on: :collection
      end
    end

    resources :skus, only: [] do
      resource :notify_me, only: [:new, :create], controller: 'products/notify_me'
    end
  
  	resources :carts, only: [] do
  		collection do
	  		get :mycart
	  		get :checkout
        %w( paypal stripe ).each do |payment|
          post "#{payment}/confirm", to: "carts/#{payment}#confirm", as: "#{payment}_confirm"
        end
  		end
  	end
    resources :cart_items, only: [:create, :update, :destroy]
    resources :delivery_service_prices, only: [:show]

  	resources :orders, only: [:destroy] do
  		member do
	  		get :retry
	  		get :confirm
	  		post :complete
  		end
      collection do
        get :success
        get :failed
      end
  		resources :addresses, only: [:new, :create, :update]
  	end

  	namespace :admin do
  		root to: "admin#dashboard"
  		authenticate :user, lambda { |u| u.role?(:admin) } do
	  		mount RedactorRails::Engine => '/redactor_rails'
	  		mount Sidekiq::Web => '/sidekiq'
  		end
	  	resources :accessories, :categories, except: :show
	  	resources :products, except: [:show, :create] do
        member do
          patch :autosave
          patch :archive
        end
	  		resources :attachments, except: :index
	  		resources :skus, except: [:index, :show] do
	  			resources :stock_adjustments, only: [:create, :new], controller: 'skus/stock_adjustments'
	  		end
	  		namespace :skus do
	  			resources :sku_variants, as: 'variants', path: 'variants', controller: :variants, only: :new do
	  				collection do
              post 'create', as: 'create'
	  					patch 'update', as: 'update'
	  					delete 'destroy', as: 'destroy'
	  				end
	  			end
	  		end
	  	end
  		resources :orders, only: [:index, :show, :update, :edit] do
        delete :cancel, to: 'orders#cancel', on: :member
      end
      resources :transactions, only: :show
  		resources :delivery_services, except: :show do
	  		collection do
	  			get :copy_countries
	  			post :set_countries
	  		end
  			resources :delivery_service_prices, path: 'prices', except: :show
  		end
  		namespace :products do
  			resources :tags, only: :index
  			resources :stock, only: [:index, :show]
        resources :stock_adjustments, only: [:new, :create]
  		end
	  	resources :pages, except: [:show, :destroy, :new, :create]
	  	get '/settings' => 'admin#settings'
	  	patch '/settings/update' => 'admin#update'
	  	get '/profile' => 'users#edit'
	  	patch '/profile/update' => 'users#update'
  	end

  	# # redirect unknown URLs to 404 error page
  	# match '*path', via: :all, to: 'errors#show', code: 404
end

app/controllers/admin/tiers_controller.rb
class Admin::TiersController < ApplicationController

  before_filter :authenticate_user!
  layout "admin"
  # GET /tiers
  # GET /tiers.json
  def index
    @tiers = Tier.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tiers }
    end
  end

  # GET /tiers/new
  # GET /tiers/new.json
  def new
    @tier = Tier.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tier }
    end
  end

  # GET /tiers/1/edit
  def edit
    @tier = Tier.find(params[:id])
  end

  # POST /tiers
  # POST /tiers.json
  def create
    @tier = Tier.new(params[:tier])

    respond_to do |format|
      if @tier.save
        format.html { redirect_to admin_tiers_url, notice: 'Tier was successfully created.' }
        format.json { render json: @tier, status: :created, location: @tier }
      else
        format.html { render action: "new" }
        format.json { render json: @tier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tiers/1
  # PUT /tiers/1.json
  def update
    @tier = Tier.find(params[:id])
    respond_to do |format|
      if @tier.update_attributes(params[:tier])
        format.html { redirect_to admin_tiers_url, notice: 'Tier was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tiers/1
  # DELETE /tiers/1.json
  def destroy
    @tier = Tier.find(params[:id])
    @tier.destroy

    respond_to do |format|
      format.html { redirect_to admin_tiers_url }
      format.json { head :no_content }
    end
  end
end

app/views/admin/tiers/_form.html.haml
.row-fluid
  .col-md-6
    = form_for [:admin, @tier], :html => { :class => 'form-horizontal', :role => 'form' } do |f|
      %fieldset
      - if @tier.errors.any?
        #error_explanation
          %h2= "#{pluralize(@tier.errors.count, "error")} prohibited this tier from being saved:"
          %ul
            - @tier.errors.full_messages.each do |msg|
              %li= msg
      .form-group
        = f.label :length_start, :class => 'control-label col-md-3'
        .col-md-9
          = f.text_field :length_start, :class => 'form-control'
      .form-group
        = f.label :length_end, :class => 'control-label col-md-3'
        .col-md-9
          = f.text_field :length_end, :class => 'form-control'
      .form-group
        = f.label :weight_start, :class => 'control-label col-md-3'
        .col-md-9
          = f.text_field :weight_start, :class => 'form-control'
      .form-group
        = f.label :weight_end, :class => 'control-label col-md-3'
        .col-md-9
          = f.text_field :weight_end, :class => 'form-control'
      .form-group
        = f.label :thickness_start, :class => 'control-label col-md-3'
        .col-md-9
          = f.text_field :thickness_start, :class => 'form-control'
      .form-group
        = f.label :thickness_end, :class => 'control-label col-md-3'
        .col-md-9
          = f.text_field :thickness_end, :class => 'form-control'
      .form-group
        %label.col-md-3.control-label Shipping options
        .col-md-9
          - if Shipping.active.all.empty? 
            %p No shipping options to select.
          - else
            - Shipping.active.all.each do |shipping|
              .checkbox
                %label
                = hidden_field_tag "tier[shipping_ids][]", ""
                = check_box_tag "tier[shipping_ids][]", shipping.id, @tier.shipping_ids.include?(shipping.id)
                = shipping.name
                = ' - '
                %b= format_currency shipping.price
      .form-group
        .col-md-offset-3.col-md-9
          = f.submit 'Submit', :class => 'btn btn-primary'

app/views/admin/tiers/edit.html.haml
- content_for :title, 'Edit tier'
- content_for :breadcrumb, 'Edit'
- breadcrumb_add 'Shipping tiers', admin_tiers_path
- content_for :header, "Editing tier ##{@tier.id}"
- content_for :hide_sub_navigation, 'hide_subnav'

= render 'form'

app/views/admin/tiers/index.html.haml
- content_for :title, 'Shipping tiers'
- content_for :breadcrumb, 'Shipping tiers'
- content_for :header, 'Shipping tiers'
- content_for :subnav do
  %li= link_to 'Methods', admin_shippings_path
  %li.current
    %a.current Tiers
  %li= link_to 'Countries', admin_countries_path

= link_to new_admin_tier_path, :class => "btn btn-success add_record" do
  %i.icon-plus
  New tier
- if @tiers.empty?
  %p You don't have any tiers yet
- else
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th ID
        %th Length (mm)
        %th Weight (g)
        %th Thickness (mm)
        %th Shipping option(s)
        %th
    %tbody
      - @tiers.each do |tier|
        %tr
          %td= tier.id
          %td 
            = tier.length_start
            = '- '
            = tier.length_end
          %td
            = tier.weight_start
            = ' - '
            = tier.weight_end
          %td
            = tier.thickness_start
            = ' - '
            = tier.thickness_end
          %td
            %ul 
              - tier.shippings.active.each do |shipping|
                %li
                  = shipping.name
                  = ' - '
                  %b= format_currency shipping.price
          = table_commands tier, admin_tier_path(tier), edit_admin_tier_path(tier), admin_tier_path(tier),  1

app/views/admin/tiers/new.html.haml
- content_for :title, 'New tier'
- content_for :breadcrumb, 'New'
- breadcrumb_add 'Shipping tiers', admin_tiers_path
- content_for :header, 'New tier'
- content_for :hide_sub_navigation, 'hide_subnav'

= render 'form'